# Site settings
title: Wow
email: youremailaddress@gmail.com
description: Some description
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Logo settings
logo-placeholder: images/logo.svg

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes

# Collections
collections:
  years:
    output: true
    permalink: /:title
  speakers:
    output: true
    permalink: /speakers/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      categories: ""
      tags: []
      featured-image: ""
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      featured-image: ""
  - scope:
      path: ""
      type: years
    values:
      layout: years
      tags: []
      featured-image: ""
      homepage-thumbnail: ""
  - scope:
      path: ""
      type: speakers
    values:
      layout: speakers
      name: Example Name
      short_bio: A little bio
      pic: /images/pic04.jpg
